---
title: "Strokes in Scotland Report"
author: "Lauren Davidson"
date: "09/03/2021"
output: html_document
---

----
Project Brief
----

### Aim
Use publicly available data to improve outcomes for stroke diagnoses in Scotland. 

### Question
**How can Scottish health services most effectively prevent and treat stroke diagnoses?**

### End User and outcomes
My end users are health practitioners and policy makers who are interested in:

* identifying and reproducing succesful strategies in the prevention and treatment of strokes.
* identifying demographic groups most a risk of stroke for targetted intervention.

Original brief accessible in documentation folder of this project.

### Background
"Cerebrovascular disease develops as a result of problems with the blood vessels supplying oxygen rich blood to the brain.
Scotland has a high prevalence of the risk factors associated with cerebrovascular disease such as smoking and high blood pressure. Despite a substantial decrease in rates of death over the lastdecade, treating and preventing stroke is a national clinical priority for Scotland as outlined in the Stroke Improvement Plan."
  - 2020-01-28-stroke-summary.pdf from https://beta.isdscotland.org/find-publications-and-data/conditions-and-diseases/stroke-statistics/scottish-stroke-statistics/



----
Data Summary
----

sources, structure, key issues  

----
Analysis
----

* What is the most common stroke diagnosis in Scotland?
* Are there any differences when we look at the data by health board vs by local authority?
* Are there differences in mortality rates (mortality EASR) for different types of stroke? Does this vary with demographics?
* Are there any differences in stroke diagnoses between different demographics
    1. Gender
    2. Age
    3. Gender and Age
    4. Healthboard
    5. Council
    6. SIMD
    7. Age Group and SIMD

----
Key findings and Recommendations
----

# Notable findings

*
*

# How can Scottish health services most effectively prevent and treat stroke diagnoses?
# What measures have been successful in the treatment and prevention of stroke?
# Which demographics should we target for stroke intervention?


----
Additional Information
----

# Methodology

## Metrics Chosen

mean/median

## Tools Used

## Project Structure

# Definitions

*Stroke*
* One of three possible diagnoses of Cerebrovascular diseases.
* Used in report and analysis to refer to all Cerebrovascular Diseases to aid ease of understanding.
*Subarachnoid Haemorrhage*
* One of three possible diagnoses of Cerebrovascular diseases.
*TIAs and other symptoms*
* Transient Ischemic Attacks (commonly known as mini-strokes) and other symptoms
* One of three possible diagnoses of Cerebrovascular diseases.
*Cerebrovascular Disease*
* "Cerebrovascular Disease (CVD) is a condition that develops as a result of problems with the blood vessels supplying the brain. This can cause a stroke, a transient ischaemic attack (TIA) or a subarachnoid haemorrhage."
*   - From Scottish Government Stroke Improvement Plan, 2014, accessed at https://www.gov.scot/publications/stroke-improvement-plan/pages/3/
*Crude Rate*
*EASR*
*SMR*
  
# Assumptions

* financial year can be compared to calendar year without signifcantly undermining the analysis

* ambiguously named and defined crude rates in individual datasets refer to the crude rate of the dataset's subject variable.
e.g. EASR and crude rate in mortalitybyca refer to mortality per 100,000, EASR and crude rate in activitybyca refer to discharges per 100,000 and in diagnosis-by-counil-area refer to hospital stays per 100,000.

Qualifiers removed, but could be used for extension work.

Losing detail of age groupings from hospital stays will not affect analysis /
The larger age groupings will allow for a broader, but easier to interpret analysis.

Use EASR whenever available to normalise rates by European standards.
Order of preference for adjusted metrics: EASR, SMR, crude.

Use mean as standard method of assimilating rates in order to visualise differences in demographics more clearly.

# Data Assessment

Copy from data analysis plan.