---
title: "Data Analysis Plan"
author: "Lauren Davidson"
date: "04/03/2021"
output: html_document
---

# Project Brief

## Aim
Use publicly available data to improve outcomes for stroke diagnoses in Scotland. 

## Question
*How can Scottish health services most effectively prevent and treat stroke diagnoses?*

## End User and outcomes
My end users are health practitioners and policy makers who are interested in:
* identifying and reproducing succesful strategies in the prevention and treatment of strokes.
* identifying demographic groups most a risk of stroke for targetted intervention.

See "documentation/brief.pdf" for original brief.

# Project Plan

## Project requirements

## Systems and tools to be used
* RStudio for all exploration, cleaning and analysis.
* Reports and documentation will be produced as R Markdown files.

## Data sources

* Scottish Stroke Statistics - Activity
Provider: Public Health Scotland
Time period: financial years 2009/10 - 2018/19.
Content: .csv for Council Area OR Health Board
Variables: Number of discharges and crude rate per 100,000 population by gender, age, sex and council area OR NHS board.
Usage: *Used for project*
Reason: Provided with brief.
Link: (https://www.opendata.nhs.scot/dataset/scottish-stroke-statistics)

* Scottish Stroke Statistics - Mortality
Provider: Public Health Scotland
Time period: 2009 - 2018
Content: .csv for Council Area OR Health Board
Variables: Number of mortalisies and crude rate per 100,000 population by gender, age, sex and council area OR NHS board.
Usage: *Used for project*
Reason: Provided with brief. Mortality used as a measure of outcomes.
Link: (https://www.opendata.nhs.scot/dataset/scottish-stroke-statistics)

* Inpatient and Daycare Administrative Dataset 
Provider: Public Health Scotland's Data and Intelligence
Time period: Annual data from financial years 2014/15 to 2018/19
Content: .xlsx file of 4 sheets for Council Area OR Health Board
Variables: Hospital stays and crude rate per 100,000 population by gender, age, sex and council area OR NHS board.
Usage: *Used for project*
Reason: Hospital stays provides a useful proxy for incidence rate of stroke diagnoses.
Link: (https://www.isdscotland.org/Health-Topics/Hospital-Care/Diagnoses/)

* National Stroke Statistics
Provider: Public Health Scotland's Data and Intelligence
Time period: Annual data from 2011-2020
Format: One .csv file per year and metric grouping.
Content: Information on hospital activity, operations, incidence, 30-day survival following first emergency admission, GP prescribing, mortality and ambulance service activity.
Usage: *Not used for project* 
Reason: Time required to assimilate data
Link: (https://beta.isdscotland.org/find-publications-and-data/conditions-and-diseases/stroke-statistics/scottish-stroke-statistics/)

* Quality and Outcomes Framework
Provider: Public Health Scotland's Data and Intelligence
Time period: 2004 - 2016
Format:
Content: Overall outcome meausurement for health at different levels (GP, Health board, HSCP)
Usage: *Not used for project*
Reason: Not directly relevant to question.
Link: (https://www.isdscotland.org/Health-Topics/General-Practice/Quality-And-Outcomes-Framework/)

* Scottish Stroke Improvement Programme Reports
Provider: Scottish Stroke Care Audit
Time period: 2016-2020 (additionally Scottish Stroke Care Audit: 2008-2015)
Format: Varied. Produced annually
Content: Reports improvements against stroke targets, such as number of patients receiving stroke care within time target.
Usage: *Not used for project*
Reason: Time required to assimilate data
Link: (https://www.strokeaudit.scot.nhs.uk/Reports/Reports.html)

* Waiting Times Datasets
Provider: Public Health Scotland
Time period: Varied
Format: Varied
Content: Diagnostic waiting times - endoscopy and radiology only
Stage of Treatment- completed waits by specialism
Monthly Emergency Dept Activiity and Waiting times - the number of attendances that are admitted, transferred or discharged within four hours of arrival.
18 weeks to referal - number of patients who started treatment within 18 weeks of referral
Usage: *Not used for project*
Reason: Time required to assimilate data
Link: (https://www.opendata.nhs.scot/organization/isd?q=waiting+times&sort=score+desc%2C+metadata_modified+desc)

* Scottish Health Survey
Provider: Scottish Government
Time period: 2011- 2020
Format: Varied
Content: self-reported measure of health, alcohol, mental wellbeing, activity, diet, smoking, etc
Usage: *Not used for project*
Reason: Not directly relevant to question.
Link:  (https://www.gov.scot/collections/scottish-health-survey/)

## Definitions and assumptions

## Stroke
 "Cerebrovascular Disease (CVD) is a condition that develops as a result of problems with the blood vessels supplying the brain. This can cause a stroke, a transient ischaemic attack (TIA) or a subarachnoid haemorrhage."

## Derived business questions and how these will be answered with available data

# Data quality 

# Data bias

# Data structure

# Domain expert collaboration